lightgbm_classifier:
  objective: "binary"
  metric: "auc"
  boosting_type: "gbdt"
  num_leaves: 63
  learning_rate: 0.02
  feature_fraction: 0.8
  bagging_fraction: 0.7
  bagging_freq: 1
  lambda_l1: 0.1
  lambda_l2: 0.1
  min_gain_to_split: 0.01
  min_child_samples: 20
  n_estimators: 500
  n_jobs: -1
  seed: 42
  verbose: -1

gnn_collusion_detector:
  model_type: "GraphSAGE"
  hidden_channels: 128
  num_layers: 3
  dropout: 0.3
  learning_rate: 0.005
  epochs: 100
  weight_decay: 0.0005
  batch_size: 128
  optimizer: "Adam"
  loss_function: "BCEWithLogitsLoss"
  node_features_dim: 16
  edge_features_dim: 4

ensemble_strategy:
  method: "weighted_average"
  lightgbm_weight: 0.6
  gnn_weight: 0.4
  threshold_adjustment_factor: 0.05