environment:
  name: "development"
  debug_mode: true
  log_level: "DEBUG"
  kafka_brokers: "localhost:9092"
  kafka_input_topic: "snapp.events.dev"
  kafka_output_topic: "snapp.fraud_alerts.dev"
  redis_host: "localhost"
  redis_port: 6379
  mlflow_tracking_uri: "http://localhost:5000"
  model_storage_path: "file:///mlruns_dev"
  feature_store_type: "redis"
  database_url: "postgresql://fraud_dev:dev_password@localhost:5432/fraud_dev"
  api_host: "localhost"
  api_port: 8000

model_config:
  use_global_params: true

thresholds:
  use_global_thresholds: true